name: Deploy API (reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, deploy]
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v6
      - name: copy repository
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "api/*"
          target: "${{ vars.DEPLOY_PATH }}/api"
          strip_components: 1
          rm: true
      - name: install dependencies
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd "${{ vars.DEPLOY_PATH }}/api"
            ~/.local/bin/uv sync
      - name: restart the service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            systemctl --user restart zabmap.service
