name: Deploy GUI (reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, deploy]
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: install dependencies
        run: |
          cd gui
          npm install --omit=dev --cache /tmp/npm-cache
      - name: build the site
        run: |
          cd gui
          npm run build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_BASE_URL: ${{ vars.VITE_BASE_URL }}
          VITE_OIDC_AUTHORITY: ${{ vars.VITE_OIDC_AUTHORITY }}
          VITE_OIDC_CLIENT_ID: ${{ vars.VITE_OIDC_CLIENT_ID }}
          VITE_OIDC_REDIRECT_URI: ${{ vars.VITE_OIDC_REDIRECT_URI }}
      - name: copy build to the server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "gui/dist/*"
          strip_components: 2
          target: "${{ vars.DEPLOY_PATH }}/gui"
          rm: true
