name: Deploy API (dev)

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy_api_reusable.yml
    with:
      environment: development
    secrets: inherit
